### ISSUE TITLE
Proxy always returns gzipped content

### ISSUE THREAD

**Issue by st3fan** [mozilla/esFrontLine#2]
Even though I am not requesting compressed responses (by setting the `Accept-Encoding` header), the proxy still returns gzipped content:

```
curl -v -XGET -d '{"query": { "term": { "priority": "xxp4" } }}' "http://127.0.0.1:9292/bugs20121030/_search"
* About to connect() to 127.0.0.1 port 9292 (#0)
*   Trying 127.0.0.1...
* Adding handle: conn: 0x17f7ad0
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x17f7ad0) send_pipe: 1, recv_pipe: 0
* Connected to 127.0.0.1 (127.0.0.1) port 9292 (#0)
> GET /bugs20121030/_search HTTP/1.1
> User-Agent: curl/7.32.0
> Host: 127.0.0.1:9292
> Accept: */*
> Content-Length: 45
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 45 out of 45 bytes
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< content-length: 122
< content-type: application/json; charset=UTF-8
< access-control-allow-origin: *
< content-encoding: gzip
< Server: Werkzeug/0.9.4 Python/2.7.5+
< Date: Wed, 13 Nov 2013 20:50:10 GMT
<
�L�A ... Compressed content follows
```

From a HTTP point of view this is not correct. This will also break clients and libraries. (Like `curl` for example)

**Comment by klahnakoski** [comment]
Assuming this is the Metrics cluster, the always-return-gzip problem is how the ES cluster was setup.  esFrontLine is not smart enough to know what it is sending back to the client.

On another note, your GET did not state the desired content-encoding, I would assume the server can choose he encoding in that situation.

**Comment by st3fan** [comment]
I don't think that is correct. If a request does not specify `Accept-Encoding` then a service should not return content that the client can possibly not use.

I figured out what really happens. It has nothing to do with the ES cluster but with the way you proxy requests: you use the Python Requests library to call ES, and that library by default sends an `Accept-Encoding: gzip`. This is normally fine but in the case of proxying requests what should really happen is that you honour the encoding wishes of the original request that you received.

The current behaviour confuses http clients.

**Comment by klahnakoski** [comment]
This is now a bug
