### ISSUE TITLE
Missing import of sys

### ISSUE THREAD

**Issue by st3fan** [mozilla/esFrontLine#3]
In the `remove_util` branch there is a missing `import sys` in `app.py`. This is triggered by having the following in your `settings.py` (taken from the README):

```
    "debug":{
        "log":[{
            "class":"esFrontLine.util.logs.Log_usingStream",
            "stream":"sys.stdout"
        }]
    }
```

The app fails with a cryptic message:

```
__init__() got an unexpected keyword argument 'class'
```

But what really happens is:

```
Traceback (most recent call last):
  File "app.py", line 184, in <module>
    ch = logging.StreamHandler(stream=eval(d["stream"]))
  File "<string>", line 1, in <module>
NameError: name 'sys' is not defined
```

**Comment by klahnakoski** [comment]
Sorry you had to find this.  It is fixed.  remove_util branch has been merged to master.  The code is now running at klahnakoski-es.corp.tor1.mozilla.com:9292  (toronto office) and points the the metrics cluster.
