### ISSUE TITLE
Add Hawk Credential Verification

### ISSUE THREAD

**Issue by klahnakoski** [mozilla/esFrontLine#6]
Use [mohawk](https://mohawk.readthedocs.io/en/latest/) for  http authentication.  [MoDataSubmission](https://github.com/klahnakoski/MoDataSubmission) has both client and server implementations

**Comment by klahnakoski** [comment]
To deploy on the new ActiveData server, use the [frontend6](https://github.com/mozilla/ActiveData/tree/frontend6) branch:

1. Update [setup_frontend_r3_large.sh](https://github.com/mozilla/ActiveData/blob/frontend6/resources/scripts/setup_frontend_r3_large.sh) to include all instructions for installation
2. Add another `upstream` to [nginx config](https://github.com/mozilla/ActiveData/blob/frontend6/resources/config/nginx.conf) that will direct traffic to the esFrontLine app

**Comment by La0** [comment]
@klahnakoski I can start working on that to enable ES access from code coverage backend.

**Comment by klahnakoski** [comment]
This is done
